### ISSUE TITLE
Classpath / Linking exception

### ISSUE THREAD

**Issue by sirinath** [graalvm/fastr#1]
Can the license be changed so there is a classpath and linking exception. Or ideally make it ASL 2.0, MIT, BSD which mean this can be used to develop your own language using and perhaps copying and adopting some of the constructs from this.

**Comment by lukasstadler** [comment]
we would like to put a more permissive license on FastR, but it is a derivative of the original GNUR, so we cannot change the license away from GPLv2.

**Comment by sirinath** [comment]
Can you re implement if it is feasible?

**Comment by lukasstadler** [comment]
AFAIK, the only reimplementation of R that is not a derivative of GNUR is TIBCO's TERR, and they put a huge amount of work into it.

(I am not a lawyer...) the problem is that there is no thorough specification of the R language and the functionality in the core packages. some of this can be determined by looking at the behavior of the system, but for many things it is very hard to determine how they really work without looking at GNUR source code or copying GNUR source code.

getting rid of all GNUR-derivative code in FastR would be a very large undertaking, and is not one of our goals at the moment.
